using System.Collections.Generic;
using System.Globalization;

namespace CringometrMDSPC
{
    public static class LocalizationManager
    {
        public static CultureInfo CurrentCulture { get; private set; } = new CultureInfo("pl-PL"); // Domyślnie polski

        private static readonly Dictionary<string, Dictionary<string, string>> _localizedStrings = new Dictionary<string, Dictionary<string, string>>();

        static LocalizationManager()
        {
            // Polskie ciągi znaków
            _localizedStrings["pl-PL"] = new Dictionary<string, string>
            {
                // Form1 UI
                {"AppTitle", "CRINGOMETR 3.0 ULTRA - C# OFFLINE"},
                {"DataPath", "Dane: "},
                {"VerdictACC5", "ACC 5 - DESTRUKCJA MÓZGU"},
                {"VerdictACC4", "ACC 4 - KRYTYCZNY CRINGE"},
                {"VerdictACC3", "ACC 3 - PLAGIAT / SCAM"},
                {"VerdictACC2", "ACC 2 - PODEJRZANE"},
                {"VerdictACC1", "ACC 1 - CZYSTA INŻYNIERIA"},
                {"SectionScanning", "Skanowanie"},
                {"ButtonRebuildDatabase", "Przebuduj bazę"},
                {"ButtonPickFiles", "Wybierz pliki"},
                {"ButtonScanScanFolder", "Skanuj DO_SKANOWANIA"},
                {"ButtonOpenScanFolder", "Otwórz DO_SKANOWANIA"},
                {"ButtonOpenReportsFolder", "Otwórz RAPORTY"},
                {"ButtonEditTemplate", "Edytuj szablon"},
                {"TemplateEditorTitle", "Edytor słów kluczowych"},
                {"TemplateEditorLabel", "Słowa (oddzielone przecinkiem):"},
                {"SectionURL", "URL"},
                {"PlaceholderURL", "Wklej URL obrazu/wideo"},
                {"ButtonDownloadURL", "Pobierz URL"},
                {"SectionActiveLearning", "Active Learning"},
                {"ButtonRateGood", "Oceń jako DOBRE"},
                {"ButtonRateBad", "Oceń jako ZŁE"},
                {"ButtonRateCritical", "Oceń jako KRYTYCZNE"},
                {"SectionCed", "Baza CED"},
                {"ButtonExportCed", "Eksportuj CED"},
                {"ButtonLoadCed", "Wczytaj CED"},
                {"SectionCedCreator", "Kreator Nowej Paczki (.CED)"},
                {"ButtonStageGood", "Dodaj do DOBRE"},
                {"ButtonStageBad", "Dodaj do ZŁE"},
                {"ButtonStageCritical", "Dodaj do KRYTYCZNE"},
                {"ButtonBuildCed", "BUDUJ I ŁADUJ PACZKĘ"},
                {"LogCreatorAdded", "[KREATOR] Dodano {0} plików. Razem w tej kategorii: {1}"},
                {"LogCreatorNoFiles", "[KREATOR] Nie dodano żadnych plików!"},
                {"LogCreatorCreated", "[KREATOR] Paczka utworzona: {0}"},
                {"LogCreatorImporting", "[KREATOR] Natychmiastowy import addytywny..."},
                {"LogCreatorError", "[BŁĄD KREATORA] {0}"},
                {"LogCedExported", "[CED] Baza wyeksportowana do: {0}"},
                {"LogCedImported", "[CED] Baza wczytana pomyślnie. Przeładowuję..."},
                {"LogCedAutoLoading", "[CED] Wykryto domyślną bazę default.ced. Wczytywanie..."},
                {"LogCedError", "[BŁĄD CED] {0}"},
                {"LogBaseSkip", "[BAZA] Pomijam {0}: {1}"},
                {"SectionExport", "Eksport"},
                {"ButtonExportZip", "Eksport ZIP"},
                {"SectionInfo", "Informacje"},
                {"ButtonAbout", "O programie"},
                {"ButtonToggleCamera", "Kamera na żywo"},
                {"ButtonScanCamera", "Skanuj teraz (KAM)"},
                {"Modules", "Moduły: CLIP {0} | wideo {1} | audio {2} | 3D {3} | raporty {4}"},
                {"TabHistory", "Historia"},
                {"TabLog", "Log"},
                {"GridColumnFile", "Plik"},
                {"GridColumnType", "Typ"},
                {"GridColumnBDPM", "BDPM"},
                {"GridColumnVerdict", "Werdykt"},
                {"GridColumnDetails", "Szczegóły"},
                {"LogBoot", "[BOOT] CRINGOMETR 3.0 ULTRA załadowany. System gotowy do eksterminacji żenady."},
                {"LogInfoExamples", "[INFO] Wrzuć przykłady do Baza_Danych/DOBRE, /ZLE, /KRYTYCZNE — system się ich uczy."},
                {"LogInfoChart", "[INFO] Kliknij 📊 LIVE WYKRES aby otworzyć panel live wykresu."},
                {"LogInfoReload", "[INFO] Po dorzuceniu nowych zdjęć kliknij ↻ PRZEŁADUJ BAZĘ."},
                {"LogLanguageChanged", "[JĘZYK] Zmieniono język na: {0}"},
                {"LogBaseScanning", "[BAZA] Skanuję foldery referencyjne..."},
                {"LogBaseLoaded", "[BAZA] Wczytane: DOBRE={0}, ZLE={1}, KRYTYCZNE={2}"},
                {"LogBaseEmptyWarning", "[BAZA] Brak obrazów referencyjnych. Wyniki obrazów będą zerowe, dopóki nie dodasz przykładów."},
                {"LogBaseError", "[BŁĄD BAZY] {0}"},
                {"LogPickFilesFilter", "Obsługiwane pliki|*.jpg;*.jpeg;*.png;*.bmp;*.webp;*.mp4;*.avi;*.mov;*.mkv;*.webm;*.obj;*.bbmodel|Wszystkie pliki|*.*"},
                {"LogScanFolderEmpty", "[SKAN] Folder DO_SKANOWANIA jest pusty albo nie ma obsługiwanych plików."},
                {"LogAuditStart", "--- START AUDYTU: {0} plików ---"},
                {"LogScanFile", "[SKAN] {0}"},
                {"LogAnalysisError", "Błąd analizy: {0}"},
                {"LogAuditEnd", "--- KONIEC AUDYTU. Najwyższy BDPM: {0} ---"},
                {"LogReportSummary", "[RAPORT] Raport zbiorczy: {0}"},
                {"LogDownloadURLPrompt", "[POBIERANIE] Wklej URL do pobrania."},
                {"LogDownloadURLStart", "[POBIERANIE] Start: {0}"},
                {"LogDownloadURLSuccess", "[POBIERANIE] Pobrano: {0} -> DO_SKANOWANIA"},
                {"LogDownloadURLError", "[BŁĄD POBIERANIA] {0}"},
                {"LogActiveLearningNoFile", "[ACTIVE LEARNING] Brak aktualnego pliku albo podglądu do zapisania."},
                {"LogActiveLearningNoPreview", "[ACTIVE LEARNING] Ten wynik nie ma obrazu ani klatki podglądu do zapisania."},
                {"LogOCRDetected", "[OCR] Wykryto słowa kluczowe na obrazie: {0}"},
                {"LogActiveLearningSaved", "[ACTIVE LEARNING] Zapisano do {0}: {1}"},
                {"LogActiveLearningError", "[ACTIVE LEARNING] Błąd: {0}"},
                {"LogExportZipPreparing", "[EKSPORT] Przygotowuję archiwum ZIP w tle..."},
                {"LogExportZipReady", "[EKSPORT] ZIP gotowy: {0}"},
                {"LogExportZipError", "[EKSPORT] Błąd: {0}"},
                {"LogResult", "[WYNIK] {0}: {1} BDPM | {2} | {3}"},
                {"InfoAboutTitle", "Informacje o programie"},
                {"InfoAboutDescription", "Cringometr 3.0 ULTRA - Offline AI Cringe Detector"},
                {"InfoAboutCopyright", "Copyright © MDSPC 2026"},
                {"InfoAboutTrademark", "Ministerstwo Do Spraw Powstrzymywania Cringu"},
                {"InfoAboutAuthor", "Autor: Adam Ciepielak"},
                {"InfoAboutAIModel", "Model AI: CLIP (OpenAI)"},
                {"InfoAboutLibraries", "Biblioteki: ONNX Runtime, System.Drawing, System.Windows.Forms"},
                {"InfoAboutSupport", "Wsparcie: FFmpeg (dla wideo/audio)"},
                {"InfoAboutDisclaimer", "Ten program jest własnością Ministerstwa Do Spraw Powstrzymywania Cringu i jest przeznaczony do używania prywatnego. Nieautoryzowane rozpowszechnianie, modyfikowanie lub używanie w celach komercyjnych jest zabronione."},
                {"InfoAboutBuild", "build 2026 Adam Ciepielak"},
                {"PreviewNoSignal", "Brak sygnału wideo"},
                {"PreviewWaiting", "Oczekiwanie na dane..."},
                {"PreviewLiveSignal", "Sygnał LIVE z kamery"},
                {"PreviewCameraOff", "Kamera wyłączona"},
                {"PreviewAnalysis", "Analiza: {0}"},
                {"PreviewVideoAnalysis", "Analiza wideo: {0} (klatka {1}/{2} @ {3}s)"},
                {"Preview3DAnalysis", "Analiza 3D: {0} (render {1}/{2})"},
                {"CameraOn", "[KAMERA] Włączono. Kliknij SKANUJ TERAZ aby zmierzyć."},
                {"CameraOff", "[KAMERA] Wyłączono."},
                {"CameraError", "[BŁĄD] Najpierw włącz kamerę."},
                {"VideoAnalysis", "[AI VIDEO] Analizuję: {0} ({1} klatek, {2}s) – co {3} klatek"},
                {"VideoAudioAnalysis", "[AI AUDIO] Analizuję dźwięk dla {0}..."},
                {"STTDetectedText", "[STT] Wykryty tekst: {0}"},
                {"VideoReport", "[RAPORT] Raport wideo (XLSX): {0}"},
                {"VideoResult", "[AI VIDEO] {0}: max {1} BDPM (wizualnie: {2}, audio: {3}{4}, klatek: {5})"},
                {"3DRendering", "[AI 3D] Renderuję {0} widoków dla {1}..."},
                {"3DRenderError", "[!] Nie udało się wyrenderować widoków dla {0}"},
                {"3DResult", "[AI 3D] {0}: {1} BDPM  ({2})"},
                {"3DDetectedPhrases", "Wykryto frazy: {0}"},
                {"3DNoPhrases", "Brak podejrzanych fraz w tekście modelu."},
                {"SkippedFile", "[POMIJAM] {0}"},
                {"SkippedModuleDisabled", "Moduł {0} wyłączony w Boot Managerze."},
                {"SkippedFFmpegMissing", "Brak ffmpeg.exe w katalogu aplikacji lub PATH. Analiza wideo wymaga FFmpeg."},
                {"Skipped3DReadError", "Błąd czytania modelu 3D: {0}"},
                {"SkippedUnsupportedType", "Nieobsługiwany typ pliku."},
                {"ImageAnalysis", "[AI] {0}: {1} BDPM  ({2})"},
                {"LearningAutoCritical", "[LEARNING] Auto-nauka: {0} → KRYTYCZNE (Wykryto skrajne stężenie)"},
                {"LearningAutoGood", "[LEARNING] Auto-nauka: {0} → DOBRE (Wykryto wysoką jakość)"},
                {"LearningVideoAutoCritical", "[LEARNING] Auto-nauka: Wideo {0} → KRYTYCZNE"},
                {"LearningCameraFrame", "[ACTIVE LEARNING] Klatka z kamery → {0} ({1})"},
                {"LearningNoActiveFileOrFrame", "[ACTIVE LEARNING] Brak aktywnego pliku ani klatki kamery do oceny."},
                {"LearningNoImageOrPreview", "[ACTIVE LEARNING] Ten wynik nie ma obrazu ani klatki podglądu do zapisania."},
                {"LiveChartTitle", "LIVE BDPM"},
                {"LiveChartWaiting", "Oczekiwanie na wyniki skanowania..."},
                {"LiveChartMax", "MAX {0} BDPM | {1}{2}"},
                {"LiveChartBDPM", "BDPM"},
                {"LiveChartSec", "Sekunda"},
                {"LiveChartVisualBDPM", "BDPM Wizualny"},
                {"LiveChartDetectedText", "Wykryty_Tekst"},
                {"LiveChartAudioBDPM", "BDPM_Audio"},
                {"LiveChartVolumeDBFS", "Glosnosc_dBFS"},
                {"LiveChartAnalysis", "Analiza"},
                {"LiveChartVideoAnalysis", "Analiza Cringe-u: {0}"},
                {"LiveChartReportSaved", "[RAPORT] Excel z wykresem: {0}"},
                {"LiveChartReportError", "[BŁĄD RAPORTU] {0}"},
                {"LiveChartSummaryReportSaved", "[RAPORT] Raport zbiorczy: {0}"},
                {"LiveChartSummaryReportError", "[BŁĄD RAPORTU] {0}"},
                {"LiveChartOpenPrompt", "[WYKRES] Najpierw otwórz live wykres (📊 LIVE WYKRES)."},
                {"LiveChartSaved", "[WYKRES] Zapisano: {0}"},
                {"LiveChartInstallMatplotlib", "[!] Zainstaluj matplotlib: pip install matplotlib"},
                {"BootManagerTitle", "Cringometr 3.0 — Boot Manager"},
                {"BootManagerSubtitle", "KONFIGURACJA MODUŁÓW AI"},
                {"BootManagerCLIP", "🧠 Model AI CLIP (Analiza wizualna)"},
                {"BootManagerVideo", "🎬 Analiza wideo (FFmpeg)"},
                {"BootManagerAudio", "🔊 Analiza Audio (Wymaga FFmpeg)"},
                {"BootManagerSTT", "🎙️  Rozpoznawanie mowy (STT)"},
                {"BootManagerOCR", "📝 Rozpoznawanie tekstu (OCR)"},
                {"BootManager3D", "📦 Skanowanie modeli 3D (.obj)"},
                {"BootManagerReports", "📊 Raporty Excel (Pandas)"},
                {"BootManagerPlots", "📈 Live Wykres (Matplotlib)"},
                {"BootManagerURLDownload", "🌐 Pobieranie plików z URL"},
                {"BootManagerFps", "Klatki na sekundę (analiza wideo):"},
                {"BootManagerStart", "▶  URUCHOM SYSTEM"},
                {"BootManagerHint", "Pierwsze uruchomienie pobierze model CLIP, potem działa offline."},
                {"BootManagerFFmpegWarning", "[!] OSTRZEŻENIE: FFmpeg nie wykryty w PATH. Analiza audio niemożliwa."},
                {"BootManagerSTTError", "[Błąd STT: wymagane połączenie internetowe dla Google API]"},
                {"BootManagerFFmpegError", "[Błąd: Brak zainstalowanego FFmpeg w systemie!]"},
                {"BootManagerSpeechUnclear", "[Mowa niewyraźna / brak mowy]"},
                {"BootManager3DModelExport", "[3D] .bbmodel: wyeksportuj do .obj w Blockbench."},
                {"BootManager3DRenderError", "[3D] Błąd renderowania: {0}"},
                {"BootManagerNoLibs", "Brak bibliotek (pydub/speech_recognition)"},
                {"BootManagerCLIPError", "[BOOT] Błąd ładowania CLIP: {0}"},
                {"BootManagerCLIPReady", "[BOOT] Model CLIP gotowy na urządzeniu: {0}. Tryb OFFLINE."},
                {"BootManagerCLIPDownload", "[BOOT] Ładuję model CLIP... (pierwsze uruchomienie pobiera ~600MB)"},
                {"ClipDownloadProgress", "[CLIP] Pobrano {0} / {1} MB"},
                {"ClipDownloadProgressNoTotal", "[CLIP] Pobrano {0} MB"},
                {"ClipDownloadStart", "[CLIP] Pobieram model ONNX clip-vit-base-patch32 (~350 MB). Kolejne uruchomienia będą offline."},
                {"ClipDownloadSaved", "[CLIP] Model zapisany: {0}"},
                {"ClipModelReady", "[CLIP] Model gotowy: {0} | {1} -> {2}"},
                {"ClipNo512DOutput", "Nie znaleziono wyjścia CLIP image_embeds 512D. Dostępne wyjścia: {0}"},
                {"ClipInvalidEmbedding", "Model CLIP nie zwrócił embeddingu image_embeds 512D. Liczba wartości: {0}"},
                {"BaseEmpty", "BAZA PUSTA — wrzuć przykłady do Baza_Danych/"},
                {"FrameSkipped", "Pominięte"},
                {"ModuleImage", "obrazu"},
                {"ModuleVideo", "wideo"},
                {"Module3D", "3D"},
                {"TypeImage", "Obraz"},
                {"TypeVideo", "Wideo"},
                {"TypeVideoFrame", "Klatka wideo"},
                {"Type3DModel", "Model 3D"},
                {"Type3DRender", "Render 3D"},
                {"Type3DDetails", "{0} | Wizualnie: {1} BDPM"},
                {"TypeVideoDetails", "Wizualnie: {0} | Audio: {1}{2} | Klatek: {3}"},
                {"LogFFmpegError", "[BŁĄD FFmpeg] {0}"},
                {"LogClipModelPath", "[MODEL] Ścieżka modelu CLIP: {0}"},
                {"LogNewVersionAvailable", "[AKTUALIZACJA] Dostępna nowa wersja: {0}."},
                {"NewVersionTitle", "Dostępna aktualizacja"},
                {"NewVersionMessage", "Dostępna jest nowa wersja aplikacji ({0}). Czy chcesz otworzyć stronę pobierania?"},
            };

            // Angielskie ciągi znaków
            _localizedStrings["en-US"] = new Dictionary<string, string>
            {
                // Form1 UI
                {"AppTitle", "CRINGOMETR 3.0 ULTRA - C# OFFLINE"},
                {"DataPath", "Data: "},
                {"VerdictACC5", "ACC 5 - BRAIN DESTRUCTION"},
                {"VerdictACC4", "ACC 4 - CRITICAL CRINGE"},
                {"VerdictACC3", "ACC 3 - PLAGIARISM / SCAM"},
                {"VerdictACC2", "ACC 2 - SUSPICIOUS"},
                {"VerdictACC1", "ACC 1 - PURE ENGINEERING"},
                {"SectionScanning", "Scanning"},
                {"ButtonRebuildDatabase", "Rebuild Database"},
                {"ButtonPickFiles", "Pick Files"},
                {"ButtonScanScanFolder", "Scan TO_SCAN Folder"},
                {"ButtonOpenScanFolder", "Open TO_SCAN Folder"},
                {"ButtonOpenReportsFolder", "Open REPORTS Folder"},
                {"ButtonEditTemplate", "Edit template"},
                {"TemplateEditorTitle", "Keyword Editor"},
                {"TemplateEditorLabel", "Keywords (comma separated):"},
                {"SectionURL", "URL"},
                {"PlaceholderURL", "Paste image/video URL"},
                {"ButtonDownloadURL", "Download URL"},
                {"SectionActiveLearning", "Active Learning"},
                {"ButtonRateGood", "Rate as GOOD"},
                {"ButtonRateBad", "Rate as BAD"},
                {"ButtonRateCritical", "Rate as CRITICAL"},
                {"SectionCed", "CED Database"},
                {"ButtonExportCed", "Export CED"},
                {"ButtonLoadCed", "Load CED"},
                {"SectionCedCreator", "New Package Creator (.CED)"},
                {"ButtonStageGood", "Add to GOOD"},
                {"ButtonStageBad", "Add to BAD"},
                {"ButtonStageCritical", "Add to CRITICAL"},
                {"ButtonBuildCed", "BUILD AND LOAD PACKAGE"},
                {"LogCreatorAdded", "[CREATOR] Added {0} files. Total in this category: {1}"},
                {"LogCreatorNoFiles", "[CREATOR] No files added!"},
                {"LogCreatorCreated", "[CREATOR] Package created: {0}"},
                {"LogCreatorImporting", "[CREATOR] Immediate additive import..."},
                {"LogCreatorError", "[CREATOR ERROR] {0}"},
                {"LogCedExported", "[CED] Database exported to: {0}"},
                {"LogCedImported", "[CED] Database loaded successfully. Reloading..."},
                {"LogCedAutoLoading", "[CED] default.ced detected. Loading..."},
                {"LogCedError", "[CED ERROR] {0}"},
                {"LogBaseSkip", "[DATABASE] Skipping {0}: {1}"},
                {"SectionExport", "Export"},
                {"ButtonExportZip", "Export ZIP"},
                {"SectionInfo", "Information"},
                {"ButtonAbout", "About"},
                {"ButtonToggleCamera", "Live Camera"},
                {"ButtonScanCamera", "Scan Now (CAM)"},
                {"Modules", "Modules: CLIP {0} | video {1} | audio {2} | 3D {3} | reports {4}"},
                {"TabHistory", "History"},
                {"TabLog", "Log"},
                {"GridColumnFile", "File"},
                {"GridColumnType", "Type"},
                {"GridColumnBDPM", "BDPM"},
                {"GridColumnVerdict", "Verdict"},
                {"GridColumnDetails", "Details"},
                {"LogBoot", "[BOOT] CRINGOMETR 3.0 ULTRA loaded. System ready to exterminate cringe."},
                {"LogInfoExamples", "[INFO] Put examples into Baza_Danych/GOOD, /BAD, /CRITICAL — the system learns from them."},
                {"LogInfoChart", "[INFO] Click 📊 LIVE CHART to open the live chart panel."},
                {"LogInfoReload", "[INFO] After adding new images, click ↻ REBUILD DATABASE."},
                {"LogLanguageChanged", "[LANGUAGE] Language changed to: {0}"},
                {"LogBaseScanning", "[DATABASE] Scanning reference folders..."},
                {"LogBaseLoaded", "[DATABASE] Loaded: GOOD={0}, BAD={1}, CRITICAL={2}"},
                {"LogBaseEmptyWarning", "[DATABASE] No reference images. Image results will be zero until you add examples."},
                {"LogBaseError", "[DATABASE ERROR] {0}"},
                {"LogPickFilesFilter", "Supported files|*.jpg;*.jpeg;*.png;*.bmp;*.webp;*.mp4;*.avi;*.mov;*.mkv;*.webm;*.obj;*.bbmodel|All files|*.*"},
                {"LogScanFolderEmpty", "[SCAN] TO_SCAN folder is empty or contains no supported files."},
                {"LogAuditStart", "--- AUDIT START: {0} files ---"},
                {"LogScanFile", "[SCAN] {0}"},
                {"LogAnalysisError", "Analysis error: {0}"},
                {"LogAuditEnd", "--- AUDIT END. Highest BDPM: {0} ---"},
                {"LogReportSummary", "[REPORT] Summary report: {0}"},
                {"LogDownloadURLPrompt", "[DOWNLOAD] Paste URL to download."},
                {"LogDownloadURLStart", "[DOWNLOAD] Start: {0}"},
                {"LogDownloadURLSuccess", "[DOWNLOAD] Downloaded: {0} -> TO_SCAN"},
                {"LogDownloadURLError", "[DOWNLOAD ERROR] {0}"},
                {"LogActiveLearningNoFile", "[ACTIVE LEARNING] No current file or preview to save."},
                {"LogActiveLearningNoPreview", "[ACTIVE LEARNING] This result has no image or preview frame to save."},
                {"LogOCRDetected", "[OCR] Keyword detected in image: {0}"},
                {"LogActiveLearningSaved", "[ACTIVE LEARNING] Saved to {0}: {1}"},
                {"LogActiveLearningError", "[ACTIVE LEARNING] Error: {0}"},
                {"LogExportZipPreparing", "[EXPORT] Preparing ZIP archive in background..."},
                {"LogExportZipReady", "[EXPORT] ZIP ready: {0}"},
                {"LogExportZipError", "[EXPORT] Error: {0}"},
                {"LogResult", "[RESULT] {0}: {1} BDPM | {2} | {3}"},
                {"InfoAboutTitle", "About Cringometr"},
                {"InfoAboutDescription", "Cringometr 3.0 ULTRA - Offline AI Cringe Detector"},
                {"InfoAboutCopyright", "Copyright © MDSPC 2026"},
                {"InfoAboutTrademark", "Ministry for Cringe Prevention"},
                {"InfoAboutAuthor", "Author: Adam Ciepielak"},
                {"InfoAboutAIModel", "AI Model: CLIP (OpenAI)"},
                {"InfoAboutLibraries", "Libraries: ONNX Runtime, System.Drawing, System.Windows.Forms"},
                {"InfoAboutSupport", "Support: FFmpeg (for video/audio)"},
                {"InfoAboutDisclaimer", "This program is property of the Ministry for Cringe Prevention and is intended for private use. Unauthorized distribution, modification, or commercial use is prohibited."},
                {"InfoAboutBuild", "build 2026 Adam Ciepielak"},
                {"PreviewNoSignal", "No video signal"},
                {"PreviewWaiting", "Waiting for data..."},
                {"PreviewLiveSignal", "LIVE signal from camera"},
                {"PreviewCameraOff", "Camera off"},
                {"PreviewAnalysis", "Analysis: {0}"},
                {"PreviewVideoAnalysis", "Video analysis: {0} (frame {1}/{2} @ {3}s)"},
                {"Preview3DAnalysis", "3D analysis: {0} (render {1}/{2})"},
                {"CameraOn", "[CAMERA] Enabled. Click SCAN NOW to measure."},
                {"CameraOff", "[CAMERA] Disabled."},
                {"CameraError", "[ERROR] Enable camera first."},
                {"VideoAnalysis", "[AI VIDEO] Analyzing: {0} ({1} frames, {2}s) – every {3} frames"},
                {"VideoAudioAnalysis", "[AI AUDIO] Analyzing audio for {0}..."},
                {"STTDetectedText", "[STT] Detected text: {0}"},
                {"VideoReport", "[REPORT] Video Report (XLSX): {0}"},
                {"VideoResult", "[AI VIDEO] {0}: max {1} BDPM (visual: {2}, audio: {3}{4}, frames: {5})"},
                {"3DRendering", "[AI 3D] Rendering {0} views for {1}..."},
                {"3DRenderError", "[!] Failed to render views for {0}"},
                {"3DResult", "[AI 3D] {0}: {1} BDPM  ({2})"},
                {"3DDetectedPhrases", "Detected phrases: {0}"},
                {"3DNoPhrases", "No suspicious phrases in model text."},
                {"SkippedFile", "[SKIPPED] {0}"},
                {"SkippedModuleDisabled", "Module {0} disabled in Boot Manager."},
                {"SkippedFFmpegMissing", "ffmpeg.exe not found in app directory or PATH. Video analysis requires FFmpeg."},
                {"Skipped3DReadError", "Error reading 3D model: {0}"},
                {"SkippedUnsupportedType", "Unsupported file type."},
                {"ImageAnalysis", "[AI] {0}: {1} BDPM  ({2})"},
                {"LearningAutoCritical", "[LEARNING] Auto-learn: {0} → CRITICAL (Extreme concentration detected)"},
                {"LearningAutoGood", "[LEARNING] Auto-learn: {0} → GOOD (High quality detected)"},
                {"LearningVideoAutoCritical", "[LEARNING] Auto-learn: Video {0} → CRITICAL"},
                {"LearningCameraFrame", "[ACTIVE LEARNING] Camera frame → {0} ({1})"},
                {"LearningNoActiveFileOrFrame", "[ACTIVE LEARNING] No active file or camera frame to rate."},
                {"LearningNoImageOrPreview", "[ACTIVE LEARNING] This result has no image or preview frame to save."},
                {"LiveChartTitle", "LIVE BDPM"},
                {"LiveChartWaiting", "Waiting for scan results..."},
                {"LiveChartMax", "MAX {0} BDPM | {1}{2}"},
                {"LiveChartBDPM", "BDPM"},
                {"LiveChartSec", "Second"},
                {"LiveChartVisualBDPM", "Visual_BDPM"},
                {"LiveChartDetectedText", "Detected_Text"},
                {"LiveChartAudioBDPM", "Audio_BDPM"},
                {"LiveChartVolumeDBFS", "Volume_dBFS"},
                {"LiveChartAnalysis", "Analysis"},
                {"LiveChartVideoAnalysis", "Cringe Analysis: {0}"},
                {"LiveChartReportSaved", "[REPORT] Excel with chart: {0}"},
                {"LiveChartReportError", "[REPORT ERROR] {0}"},
                {"LiveChartSummaryReportSaved", "[REPORT] Summary report: {0}"},
                {"LiveChartSummaryReportError", "[REPORT ERROR] {0}"},
                {"LiveChartOpenPrompt", "[CHART] First open the live chart (📊 LIVE CHART)."},
                {"LiveChartSaved", "[CHART] Saved: {0}"},
                {"LiveChartInstallMatplotlib", "[!] Install matplotlib: pip install matplotlib"},
                {"BootManagerTitle", "Cringometr 3.0 — Boot Manager"},
                {"BootManagerSubtitle", "AI MODULE CONFIGURATION"},
                {"BootManagerCLIP", "🧠 CLIP AI Model (Visual analysis)"},
                {"BootManagerVideo", "🎬 Video Analysis (FFmpeg)"},
                {"BootManagerAudio", "🔊 Audio Analysis (Requires FFmpeg)"},
                {"BootManagerSTT", "🎙️  Speech Recognition (STT)"},
                {"BootManagerOCR", "📝 Text Recognition (OCR)"},
                {"BootManager3D", "📦 3D Model Scanning (.obj)"},
                {"BootManagerReports", "📊 Excel Reports (Pandas)"},
                {"BootManagerPlots", "📈 Live Chart (Matplotlib)"},
                {"BootManagerURLDownload", "🌐 URL File Downloading"},
                {"BootManagerFps", "Frames per second (video analysis):"},
                {"BootManagerStart", "▶  START SYSTEM"},
                {"BootManagerHint", "First run downloads CLIP model, then works offline."},
                {"BootManagerFFmpegWarning", "[!] WARNING: FFmpeg not detected in PATH. Audio analysis impossible."},
                {"BootManagerSTTError", "[STT Error: internet connection required for Google API]"},
                {"BootManagerFFmpegError", "[Error: FFmpeg not installed in system!]"},
                {"BootManagerSpeechUnclear", "[Speech unclear / no speech]"},
                {"BootManager3DModelExport", "[3D] .bbmodel: export to .obj in Blockbench."},
                {"BootManager3DRenderError", "[3D] Rendering error: {0}"},
                {"BootManagerNoLibs", "Missing libraries (pydub/speech_recognition)"},
                {"BootManagerCLIPError", "[BOOT] CLIP loading error: {0}"},
                {"BootManagerCLIPReady", "[BOOT] CLIP model ready on device: {0}. OFFLINE mode."},
                {"BootManagerCLIPDownload", "[BOOT] Loading CLIP model... (first run downloads ~600MB)"},
                {"ClipDownloadProgress", "[CLIP] Downloaded {0} / {1} MB"},
                {"ClipDownloadProgressNoTotal", "[CLIP] Downloaded {0} MB"},
                {"ClipDownloadStart", "[CLIP] Downloading ONNX clip-vit-base-patch32 model (~350 MB). Subsequent runs will be offline."},
                {"ClipDownloadSaved", "[CLIP] Model saved: {0}"},
                {"ClipModelReady", "[CLIP] Model ready: {0} | {1} -> {2}"},
                {"ClipNo512DOutput", "CLIP 512D image_embeds output not found. Available outputs: {0}"},
                {"ClipInvalidEmbedding", "CLIP model did not return 512D image_embeds. Number of values: {0}"},
                {"BaseEmpty", "DATABASE EMPTY — add examples to Baza_Danych/"},
                {"FrameSkipped", "Skipped"},
                {"ModuleImage", "image"},
                {"ModuleVideo", "video"},
                {"Module3D", "3D"},
                {"TypeImage", "Image"},
                {"TypeVideo", "Video"},
                {"TypeVideoFrame", "Video Frame"},
                {"Type3DModel", "3D Model"},
                {"Type3DRender", "3D Render"},
                {"Type3DDetails", "{0} | Visual: {1} BDPM"},
                {"TypeVideoDetails", "Visual: {0} | Audio: {1}{2} | Frames: {3}"},
                {"LogFFmpegError", "[FFmpeg ERROR] {0}"},
                {"LogClipModelPath", "[MODEL] CLIP model path: {0}"},
                {"LogNewVersionAvailable", "[UPDATE] New version available: {0}."},
                {"NewVersionTitle", "Update Available"},
                {"NewVersionMessage", "A new version of the app is available ({0}). Do you want to open the download page?"},
            };
        }

        public static string GetString(string key, params object[] args)
        {
            if (_localizedStrings.TryGetValue(CurrentCulture.Name, out var dict) && dict.TryGetValue(key, out var value))
            {
                return string.Format(CurrentCulture, value, args);
            }
            // Fallback to Polish if English string is missing, or key not found
            if (_localizedStrings.TryGetValue("pl-PL", out dict) && dict.TryGetValue(key, out value))
            {
                return string.Format(CurrentCulture, value, args);
            }
            return $"[{key}]"; // Zwróć klucz, jeśli nie znaleziono tłumaczenia
        }

        public static void SetLanguage(string cultureName)
        {
            try
            {
                CurrentCulture = new CultureInfo(cultureName);
            }
            catch (CultureNotFoundException)
            {
                CurrentCulture = new CultureInfo("pl-PL"); // Powrót do polskiego
            }
        }
    }
}